database_type = 1
backing_database_name = "treaty.db"
grpc_user_service_addr_port = "0.0.0.0:50051"
grpc_data_service_addr_port = "0.0.0.0:50052"
grpc_info_service_addr_port = "0.0.0.0:50059"
http_addr = "0.0.0.0"
http_port = "50055"
admin_un = "tester"
admin_pw = "123456"
user_grpc_timeout_in_seconds = 60
data_grpc_timeout_in_seconds = 60
info_grpc_timeout_in_seconds = 60
use_grpc = true
use_http = true
override_ip_with_local = true
send_user_port_number = false 
send_data_port_number = true 
send_info_port_number = true 
jwt_valid_time_in_minutes = 20
use_tls = false 
tls_cert_path = ""
tls_key_path = ""
tls_client_cert_path = ""
tls_client_domain = "treaty"