version: '3.2'

services:
  treaty-proxy:
    container_name: treaty-proxy
    image: treaty-proxy
    ports:
    - "50051:50051"
    - "50052:50052"
    - "50055:50055"
    - "50040:50040"

  treaty-my-info:
    container_name: treaty-my-info
    image: treaty-my-info
    ports:
    - "80:80"
    depends_on:
    - treaty-proxy

  treaty-admin:
    container_name: treaty-admin
    image: treaty-admin
    ports:
    - "8081:80"

  treaty-standalone:
    container_name: treaty-standalone
    image: treaty
    ports:
    - "50061:50051"
    - "50062:50052"
    - "50065:50055"